### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [hstm/dotfiles#1]
Hello,

We recently received a vulnerability disclosure against your repository. I couldn't find an e-mail to contact or a security process to follow, so created this issue instead.

If you would like me to e-mail over the details or put them on the GitHub Issue, I'm more than happy to facilitate this for you. Otherwise, you can access the advisory [here](https://huntr.dev/bounties/1-other-hstm/dotfiles/).

It is private to you and the discloser of the report.

If you have any questions, let me know.

-- Jamie from huntr.dev

**Comment by hstm** [comment]
Hi Jamie,

Thanks for reaching out. I've removed the file in question. The password stored in this file was only for a local development instance, it isn't re-used anywhere else.

Thanks for the mindfulness, though.
Helge

**Comment by JamieSlome** [comment]
@hstm - great, would it be suitable to mark this disclosure as valid then or invalid in your eyes?

**Comment by hstm** [comment]
Technically, it was a valid disclosure.

Best,
Helge

**Comment by JamieSlome** [comment]
Great, I will reflect accordingly on our platform, cheers! 🍰
